#![allow(nonstandard_style)]

//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-rust-gen
// Home: https://github.com/gepheum/skir-rust-gen
//
// To install the Skir client library, run:
//   cargo add skir-client

// ==============================================================================
// struct GetUserRequest
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct GetUserRequest {
    pub user_id: i32,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<GetUserRequest>>,
}

impl GetUserRequest {
    pub fn default_ref() -> &'static GetUserRequest {
        static D: std::sync::LazyLock<GetUserRequest> =
            std::sync::LazyLock::new(GetUserRequest::default);
        &D
    }
}

impl GetUserRequest {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<GetUserRequest> {
        static ADAPTER: std::sync::LazyLock<
            crate::skir_client::internal::StructAdapter<GetUserRequest>,
        > = std::sync::LazyLock::new(|| {
            crate::skir_client::internal::StructAdapter::new(
                "service.skir",
                "GetUserRequest",
                "",
                |x: &GetUserRequest| &x._unrecognized,
                |x: &mut GetUserRequest, u| x._unrecognized = u,
            )
        });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<GetUserRequest> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(GetUserRequest::_adapter())
    }
}

// ==============================================================================
// struct GetUserResponse
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct GetUserResponse {
    pub user: Option<crate::skirout::base::user::User>,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<GetUserResponse>>,
}

impl GetUserResponse {
    pub fn default_ref() -> &'static GetUserResponse {
        static D: std::sync::LazyLock<GetUserResponse> =
            std::sync::LazyLock::new(GetUserResponse::default);
        &D
    }
}

impl GetUserResponse {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<GetUserResponse> {
        static ADAPTER: std::sync::LazyLock<
            crate::skir_client::internal::StructAdapter<GetUserResponse>,
        > = std::sync::LazyLock::new(|| {
            crate::skir_client::internal::StructAdapter::new(
                "service.skir",
                "GetUserResponse",
                "",
                |x: &GetUserResponse| &x._unrecognized,
                |x: &mut GetUserResponse, u| x._unrecognized = u,
            )
        });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<GetUserResponse> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(GetUserResponse::_adapter())
    }
}

// ==============================================================================
// struct AddUserRequest
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct AddUserRequest {
    pub user: crate::skirout::base::user::User,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<AddUserRequest>>,
}

impl AddUserRequest {
    pub fn default_ref() -> &'static AddUserRequest {
        static D: std::sync::LazyLock<AddUserRequest> =
            std::sync::LazyLock::new(AddUserRequest::default);
        &D
    }
}

impl AddUserRequest {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<AddUserRequest> {
        static ADAPTER: std::sync::LazyLock<
            crate::skir_client::internal::StructAdapter<AddUserRequest>,
        > = std::sync::LazyLock::new(|| {
            crate::skir_client::internal::StructAdapter::new(
                "service.skir",
                "AddUserRequest",
                "",
                |x: &AddUserRequest| &x._unrecognized,
                |x: &mut AddUserRequest, u| x._unrecognized = u,
            )
        });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<AddUserRequest> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(AddUserRequest::_adapter())
    }
}

// ==============================================================================
// struct AddUserResponse
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct AddUserResponse {
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<AddUserResponse>>,
}

impl AddUserResponse {
    pub fn default_ref() -> &'static AddUserResponse {
        static D: std::sync::LazyLock<AddUserResponse> =
            std::sync::LazyLock::new(AddUserResponse::default);
        &D
    }
}

impl AddUserResponse {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<AddUserResponse> {
        static ADAPTER: std::sync::LazyLock<
            crate::skir_client::internal::StructAdapter<AddUserResponse>,
        > = std::sync::LazyLock::new(|| {
            crate::skir_client::internal::StructAdapter::new(
                "service.skir",
                "AddUserResponse",
                "",
                |x: &AddUserResponse| &x._unrecognized,
                |x: &mut AddUserResponse, u| x._unrecognized = u,
            )
        });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<AddUserResponse> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(AddUserResponse::_adapter())
    }
}

// ==============================================================================
// initialize_module_serializers()
// ==============================================================================

fn initialize_module_serializers() {
    static INIT: std::sync::LazyLock<()> = std::sync::LazyLock::new(|| {
        unsafe {
            let a: *mut crate::skir_client::internal::StructAdapter<GetUserRequest> =
                GetUserRequest::_adapter() as *const _ as *mut _;
            (*a).add_field(
                "user_id",
                0,
                crate::skir_client::Serializer::int32(),
                "",
                |x: &GetUserRequest| &x.user_id,
                |x: &mut GetUserRequest, v| x.user_id = v,
            );
            (*a).finalize();
        }
        unsafe {
            let a: *mut crate::skir_client::internal::StructAdapter<GetUserResponse> =
                GetUserResponse::_adapter() as *const _ as *mut _;
            (*a).add_field(
                "user",
                0,
                crate::skir_client::Serializer::optional(
                    crate::skirout::base::user::User::serializer(),
                ),
                "",
                |x: &GetUserResponse| &x.user,
                |x: &mut GetUserResponse, v| x.user = v,
            );
            (*a).finalize();
        }
        unsafe {
            let a: *mut crate::skir_client::internal::StructAdapter<AddUserRequest> =
                AddUserRequest::_adapter() as *const _ as *mut _;
            (*a).add_field(
                "user",
                0,
                crate::skirout::base::user::User::serializer(),
                "",
                |x: &AddUserRequest| &x.user,
                |x: &mut AddUserRequest, v| x.user = v,
            );
            (*a).finalize();
        }
        unsafe {
            let a: *mut crate::skir_client::internal::StructAdapter<AddUserResponse> =
                AddUserResponse::_adapter() as *const _ as *mut _;
            (*a).finalize();
        }
    });
    let _ = *INIT;
}

// ==============================================================================
// Methods
// ==============================================================================

/// Returns the user with the given user_id, or an absent value if no such user
/// exists.
pub fn get_user_method() -> &'static crate::skir_client::Method<GetUserRequest, GetUserResponse> {
    static METHOD: std::sync::LazyLock<
        crate::skir_client::Method<GetUserRequest, GetUserResponse>,
    > = std::sync::LazyLock::new(|| crate::skir_client::Method {
        name: "GetUser".to_string(),
        number: 12345_i64,
        request_serializer: GetUserRequest::serializer(),
        response_serializer: GetUserResponse::serializer(),
        doc: "Returns the user with the given user_id, or an absent value if no such user\nexists."
            .to_string(),
    });
    &*METHOD
}

/// Adds a new user to the registry.
pub fn add_user_method() -> &'static crate::skir_client::Method<AddUserRequest, AddUserResponse> {
    static METHOD: std::sync::LazyLock<
        crate::skir_client::Method<AddUserRequest, AddUserResponse>,
    > = std::sync::LazyLock::new(|| crate::skir_client::Method {
        name: "AddUser".to_string(),
        number: 23456_i64,
        request_serializer: AddUserRequest::serializer(),
        response_serializer: AddUserResponse::serializer(),
        doc: "Adds a new user to the registry.".to_string(),
    });
    &*METHOD
}
