#![allow(nonstandard_style)]

//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-rust-gen
// Home: https://github.com/gepheum/skir-rust-gen
//
// To install the Skir client library, run:
//   cargo add skir-client

// ==============================================================================
// struct User.Pet
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct User_Pet {
    pub name: String,
    pub height_in_meters: f32,
    pub picture: String,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<User_Pet>>,
}

impl User_Pet {
    pub fn default_ref() -> &'static User_Pet {
        static D: std::sync::LazyLock<User_Pet> = std::sync::LazyLock::new(User_Pet::default);
        &D
    }
}

impl User_Pet {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<User_Pet> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<User_Pet>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "user.skir",
                    "User.Pet",
                    "",
                    |x: &User_Pet| &x._unrecognized,
                    |x: &mut User_Pet, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<User_Pet> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(User_Pet::_adapter())
    }
}

// ==============================================================================
// struct User
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct User {
    pub user_id: i32,
    pub name: String,
    /// A personal quote or motto chosen by the user
    pub quote: String,
    pub pets: Vec<User_Pet>,
    pub subscription_status: SubscriptionStatus,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<User>>,
}

impl User {
    pub fn default_ref() -> &'static User {
        static D: std::sync::LazyLock<User> = std::sync::LazyLock::new(User::default);
        &D
    }
}

pub struct User_byUserId;

impl crate::skir_client::KeyedVecSpec for User_byUserId {
    type Item = User;
    type StorageKey = i32;
    type Lookup = crate::skir_client::internal::CopyLookup;
    fn get_key(item: &User) -> i32 {
        item.user_id
    }
    fn key_extractor() -> &'static str {
        "user_id"
    }
    fn default_item() -> &'static User {
        User::default_ref()
    }
}

impl User {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<User> {
        static ADAPTER: std::sync::LazyLock<crate::skir_client::internal::StructAdapter<User>> =
            std::sync::LazyLock::new(|| {
                crate::skir_client::internal::StructAdapter::new(
                    "user.skir",
                    "User",
                    "",
                    |x: &User| &x._unrecognized,
                    |x: &mut User, u| x._unrecognized = u,
                )
            });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<User> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(User::_adapter())
    }
}

// ==============================================================================
// struct SubscriptionStatus.Trial
// ==============================================================================

#[derive(Clone, Debug, PartialEq)]
pub struct SubscriptionStatus_Trial {
    pub start_time: std::time::SystemTime,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<SubscriptionStatus_Trial>>,
}

impl SubscriptionStatus_Trial {
    pub fn default_ref() -> &'static SubscriptionStatus_Trial {
        static D: std::sync::LazyLock<SubscriptionStatus_Trial> =
            std::sync::LazyLock::new(SubscriptionStatus_Trial::default);
        &D
    }
}

impl Default for SubscriptionStatus_Trial {
    fn default() -> Self {
        SubscriptionStatus_Trial {
            start_time: ::std::time::SystemTime::UNIX_EPOCH,
            _unrecognized: None,
        }
    }
}

impl SubscriptionStatus_Trial {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<SubscriptionStatus_Trial>
    {
        static ADAPTER: std::sync::LazyLock<
            crate::skir_client::internal::StructAdapter<SubscriptionStatus_Trial>,
        > = std::sync::LazyLock::new(|| {
            crate::skir_client::internal::StructAdapter::new(
                "user.skir",
                "SubscriptionStatus.Trial",
                "",
                |x: &SubscriptionStatus_Trial| &x._unrecognized,
                |x: &mut SubscriptionStatus_Trial, u| x._unrecognized = u,
            )
        });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<SubscriptionStatus_Trial> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(
            SubscriptionStatus_Trial::_adapter(),
        )
    }
}

// ==============================================================================
// enum SubscriptionStatus
// ==============================================================================

#[derive(Debug, Clone, PartialEq)]
pub enum SubscriptionStatus {
    Unknown(Option<crate::skir_client::UnrecognizedVariant<SubscriptionStatus>>),
    Free,
    Trial(Box<SubscriptionStatus_Trial>),
    Premium,
}

impl Default for SubscriptionStatus {
    fn default() -> Self {
        SubscriptionStatus::Unknown(None)
    }
}

impl SubscriptionStatus {
    fn _adapter() -> &'static crate::skir_client::internal::EnumAdapter<SubscriptionStatus> {
        static ADAPTER: std::sync::LazyLock<
            crate::skir_client::internal::EnumAdapter<SubscriptionStatus>,
        > = std::sync::LazyLock::new(|| {
            crate::skir_client::internal::EnumAdapter::new(
                |x: &SubscriptionStatus| match x {
                    SubscriptionStatus::Unknown(_) => 0,
                    SubscriptionStatus::Free => 1,
                    SubscriptionStatus::Trial(_) => 2,
                    SubscriptionStatus::Premium => 3,
                },
                |u| SubscriptionStatus::Unknown(Some(u)),
                |x: &SubscriptionStatus| match x {
                    SubscriptionStatus::Unknown(Some(u)) => Some(u.as_ref()),
                    _ => None,
                },
                "user.skir",
                "SubscriptionStatus",
                "",
            )
        });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<SubscriptionStatus> {
        initialize_module_serializers();
        crate::skir_client::internal::enum_serializer_from_static(SubscriptionStatus::_adapter())
    }
}

// ==============================================================================
// struct UserHistory.Session
// ==============================================================================

#[derive(Clone, Debug, PartialEq)]
pub struct UserHistory_Session {
    pub login: std::time::SystemTime,
    pub logout: std::time::SystemTime,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<UserHistory_Session>>,
}

impl UserHistory_Session {
    pub fn default_ref() -> &'static UserHistory_Session {
        static D: std::sync::LazyLock<UserHistory_Session> =
            std::sync::LazyLock::new(UserHistory_Session::default);
        &D
    }
}

impl Default for UserHistory_Session {
    fn default() -> Self {
        UserHistory_Session {
            login: ::std::time::SystemTime::UNIX_EPOCH,
            logout: ::std::time::SystemTime::UNIX_EPOCH,
            _unrecognized: None,
        }
    }
}

impl UserHistory_Session {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<UserHistory_Session> {
        static ADAPTER: std::sync::LazyLock<
            crate::skir_client::internal::StructAdapter<UserHistory_Session>,
        > = std::sync::LazyLock::new(|| {
            crate::skir_client::internal::StructAdapter::new(
                "user.skir",
                "UserHistory.Session",
                "",
                |x: &UserHistory_Session| &x._unrecognized,
                |x: &mut UserHistory_Session, u| x._unrecognized = u,
            )
        });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<UserHistory_Session> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(UserHistory_Session::_adapter())
    }
}

// ==============================================================================
// struct UserHistory
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct UserHistory {
    pub user: User,
    pub sessions: Vec<UserHistory_Session>,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<UserHistory>>,
}

impl UserHistory {
    pub fn default_ref() -> &'static UserHistory {
        static D: std::sync::LazyLock<UserHistory> = std::sync::LazyLock::new(UserHistory::default);
        &D
    }
}

impl UserHistory {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<UserHistory> {
        static ADAPTER: std::sync::LazyLock<
            crate::skir_client::internal::StructAdapter<UserHistory>,
        > = std::sync::LazyLock::new(|| {
            crate::skir_client::internal::StructAdapter::new(
                "user.skir",
                "UserHistory",
                "",
                |x: &UserHistory| &x._unrecognized,
                |x: &mut UserHistory, u| x._unrecognized = u,
            )
        });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<UserHistory> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(UserHistory::_adapter())
    }
}

// ==============================================================================
// struct UserRegistry
// ==============================================================================

#[derive(Clone, Debug, PartialEq, Default)]
pub struct UserRegistry {
    pub users: crate::skir_client::KeyedVec<User_byUserId>,
    /// Set this to None when you're creating a struct.
    pub _unrecognized: Option<crate::skir_client::UnrecognizedFields<UserRegistry>>,
}

impl UserRegistry {
    pub fn default_ref() -> &'static UserRegistry {
        static D: std::sync::LazyLock<UserRegistry> =
            std::sync::LazyLock::new(UserRegistry::default);
        &D
    }
}

impl UserRegistry {
    fn _adapter() -> &'static crate::skir_client::internal::StructAdapter<UserRegistry> {
        static ADAPTER: std::sync::LazyLock<
            crate::skir_client::internal::StructAdapter<UserRegistry>,
        > = std::sync::LazyLock::new(|| {
            crate::skir_client::internal::StructAdapter::new(
                "user.skir",
                "UserRegistry",
                "",
                |x: &UserRegistry| &x._unrecognized,
                |x: &mut UserRegistry, u| x._unrecognized = u,
            )
        });
        &*ADAPTER
    }
    pub fn serializer() -> crate::skir_client::Serializer<UserRegistry> {
        initialize_module_serializers();
        crate::skir_client::internal::struct_serializer_from_static(UserRegistry::_adapter())
    }
}

// ==============================================================================
// initialize_module_serializers()
// ==============================================================================

fn initialize_module_serializers() {
    static INIT: std::sync::LazyLock<()> = std::sync::LazyLock::new(|| {
        unsafe {
            let a: *mut crate::skir_client::internal::StructAdapter<User_Pet> =
                User_Pet::_adapter() as *const _ as *mut _;
            (*a).add_field(
                "name",
                0,
                crate::skir_client::Serializer::string(),
                "",
                |x: &User_Pet| &x.name,
                |x: &mut User_Pet, v| x.name = v,
            );
            (*a).add_field(
                "height_in_meters",
                1,
                crate::skir_client::Serializer::float32(),
                "",
                |x: &User_Pet| &x.height_in_meters,
                |x: &mut User_Pet, v| x.height_in_meters = v,
            );
            (*a).add_field(
                "picture",
                2,
                crate::skir_client::Serializer::string(),
                "",
                |x: &User_Pet| &x.picture,
                |x: &mut User_Pet, v| x.picture = v,
            );
            (*a).finalize();
        }
        unsafe {
            let a: *mut crate::skir_client::internal::StructAdapter<User> =
                User::_adapter() as *const _ as *mut _;
            (*a).add_field(
                "user_id",
                0,
                crate::skir_client::Serializer::int32(),
                "",
                |x: &User| &x.user_id,
                |x: &mut User, v| x.user_id = v,
            );
            (*a).add_field(
                "name",
                1,
                crate::skir_client::Serializer::string(),
                "",
                |x: &User| &x.name,
                |x: &mut User, v| x.name = v,
            );
            (*a).add_field(
                "quote",
                2,
                crate::skir_client::Serializer::string(),
                "A personal quote or motto chosen by the user",
                |x: &User| &x.quote,
                |x: &mut User, v| x.quote = v,
            );
            (*a).add_field(
                "pets",
                3,
                crate::skir_client::Serializer::array(
                    crate::skir_client::internal::struct_serializer_from_static(
                        User_Pet::_adapter(),
                    ),
                ),
                "",
                |x: &User| &x.pets,
                |x: &mut User, v| x.pets = v,
            );
            (*a).add_field(
                "subscription_status",
                4,
                crate::skir_client::internal::enum_serializer_from_static(
                    SubscriptionStatus::_adapter(),
                ),
                "",
                |x: &User| &x.subscription_status,
                |x: &mut User, v| x.subscription_status = v,
            );
            (*a).finalize();
        }
        unsafe {
            let a: *mut crate::skir_client::internal::StructAdapter<SubscriptionStatus_Trial> =
                SubscriptionStatus_Trial::_adapter() as *const _ as *mut _;
            (*a).add_field(
                "start_time",
                0,
                crate::skir_client::Serializer::timestamp(),
                "",
                |x: &SubscriptionStatus_Trial| &x.start_time,
                |x: &mut SubscriptionStatus_Trial, v| x.start_time = v,
            );
            (*a).finalize();
        }
        unsafe {
            let a: *mut crate::skir_client::internal::EnumAdapter<SubscriptionStatus> =
                SubscriptionStatus::_adapter() as *const _ as *mut _;
            (*a).add_constant_variant("free", 1, 1, "", SubscriptionStatus::Free);
            (*a).add_wrapper_variant(
                "trial",
                2,
                2,
                crate::skir_client::internal::struct_serializer_from_static(
                    SubscriptionStatus_Trial::_adapter(),
                ),
                "",
                |v| SubscriptionStatus::Trial(Box::new(v)),
                |x| match x {
                    SubscriptionStatus::Trial(b) => b.as_ref(),
                    _ => unreachable!(),
                },
            );
            (*a).add_constant_variant("premium", 3, 3, "", SubscriptionStatus::Premium);
            (*a).finalize();
        }
        unsafe {
            let a: *mut crate::skir_client::internal::StructAdapter<UserHistory_Session> =
                UserHistory_Session::_adapter() as *const _ as *mut _;
            (*a).add_field(
                "login",
                0,
                crate::skir_client::Serializer::timestamp(),
                "",
                |x: &UserHistory_Session| &x.login,
                |x: &mut UserHistory_Session, v| x.login = v,
            );
            (*a).add_field(
                "logout",
                1,
                crate::skir_client::Serializer::timestamp(),
                "",
                |x: &UserHistory_Session| &x.logout,
                |x: &mut UserHistory_Session, v| x.logout = v,
            );
            (*a).finalize();
        }
        unsafe {
            let a: *mut crate::skir_client::internal::StructAdapter<UserHistory> =
                UserHistory::_adapter() as *const _ as *mut _;
            (*a).add_field(
                "user",
                0,
                crate::skir_client::internal::struct_serializer_from_static(User::_adapter()),
                "",
                |x: &UserHistory| &x.user,
                |x: &mut UserHistory, v| x.user = v,
            );
            (*a).add_field(
                "sessions",
                1,
                crate::skir_client::Serializer::array(
                    crate::skir_client::internal::struct_serializer_from_static(
                        UserHistory_Session::_adapter(),
                    ),
                ),
                "",
                |x: &UserHistory| &x.sessions,
                |x: &mut UserHistory, v| x.sessions = v,
            );
            (*a).finalize();
        }
        unsafe {
            let a: *mut crate::skir_client::internal::StructAdapter<UserRegistry> =
                UserRegistry::_adapter() as *const _ as *mut _;
            (*a).add_field("users", 0, crate::skir_client::Serializer::<crate::skir_client::KeyedVec<User_byUserId>>::keyed_array(crate::skir_client::internal::struct_serializer_from_static(User::_adapter())), "", |x: &UserRegistry| &x.users, |x: &mut UserRegistry, v| x.users = v);
            (*a).finalize();
        }
    });
    let _ = *INIT;
}

// ==============================================================================
// Constants
// ==============================================================================

/// King of the jungle
pub fn tarzan_const() -> &'static User {
    static VALUE: std::sync::LazyLock<User> = std::sync::LazyLock::new(|| {
        User::serializer().from_json("[123,\"Tarzan\",\"AAAAaAaAaAyAAAAaAaAaAyAAAAaAaAaA\",[[\"Cheeta\",1.67,\"🐒\"]],[2,[1743592409000]]]", crate::skir_client::UnrecognizedValues::Drop).unwrap()
    });
    &*VALUE
}
